const MESSAGE_TYPES = {
    PLAYER_JOINED: 1,
    LEVEL_DATA: 2,
    PLAYER_LEFT: 3,
    PLAYER_MESSAGE: 4,
    MATCH_TERMINATED: 5,

    STATE_UPDATE: 101,
};

const gameMatchScene = {
    branch_id: '0da06877-61a9-4956-bef4-e13d320f7fa9',
    name: 'Untitled',
    created: '2021-07-26T10:18:29.780Z',
    settings: {
        physics: { gravity: [0, -9.8, 0] },
        render: {
            fog_end: 1000,
            tonemapping: 0,
            skybox: null,
            fog_density: 0.01,
            gamma_correction: 1,
            exposure: 1,
            fog_start: 1,
            global_ambient: [0.2, 0.2, 0.2],
            skyboxIntensity: 1,
            fog_color: [0, 0, 0],
            lightmapMode: 1,
            fog: 'none',
            lightmapMaxResolution: 2048,
            skyboxMip: 0,
            lightmapSizeMultiplier: 16,
            skyboxRotation: [0, 0, 0],
        },
    },
    entities: {
        'd2b7f9e7-edfa-11eb-9b62-026349a27a7c': {
            position: [0, 0, 0],
            scale: [1, 1, 1],
            name: 'Game',
            parent: null,
            resource_id: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            components: {
                script: {
                    enabled: true,
                    order: ['levelBuilder', 'game'],
                    scripts: { game: { enabled: true, attributes: {} }, levelBuilder: { enabled: true, attributes: {} } },
                },
            },
            rotation: [0, 0, 0],
            tags: [],
            enabled: true,
            children: [
                '946c0121-b491-4539-8a06-53696784b41c',
                'd2b7f9e9-edfa-11eb-9b62-026349a27a7c',
                'd2b7f9ea-edfa-11eb-9b62-026349a27a7c',
                'd2b7f9eb-edfa-11eb-9b62-026349a27a7c',
                'dd544343-1c0b-4a61-a61c-52e607d88a5a',
                'f0aebd00-47c5-4405-aead-fe74fe0ef792',
            ],
        },
        '946c0121-b491-4539-8a06-53696784b41c': {
            name: 'Camera',
            tags: [],
            enabled: true,
            resource_id: '946c0121-b491-4539-8a06-53696784b41c',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            children: [],
            position: [0, 19.435571060080424, 27.735107421875],
            rotation: [-33.000001270765964, 0, 0],
            scale: [1, 1, 1],
            components: {
                camera: {
                    enabled: true,
                    clearColorBuffer: true,
                    clearColor: [0.6039215686274509, 0.5725490196078431, 0.5725490196078431, 1],
                    clearDepthBuffer: true,
                    projection: 0,
                    fov: 45,
                    frustumCulling: true,
                    orthoHeight: 4,
                    nearClip: 0.1,
                    farClip: 1000,
                    priority: 0,
                    rect: [0, 0, 1, 1],
                    layers: [0, 1, 2, 3, 4],
                },
            },
        },
        'd2b7f9e9-edfa-11eb-9b62-026349a27a7c': {
            position: [2, 2, -2],
            scale: [1, 1, 1],
            name: 'Light',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            resource_id: 'd2b7f9e9-edfa-11eb-9b62-026349a27a7c',
            components: {
                light: {
                    castShadows: true,
                    isStatic: false,
                    vsmBlurSize: 11,
                    shadowUpdateMode: 2,
                    normalOffsetBias: 0.05,
                    color: [1, 1, 1],
                    numCascades: 1,
                    outerConeAngle: 45,
                    affectDynamic: true,
                    intensity: 1,
                    bakeDir: true,
                    cookieAngle: 0,
                    affectLightmapped: false,
                    cookieChannel: 'rgb',
                    innerConeAngle: 40,
                    shadowBias: 0.2,
                    bake: false,
                    falloffMode: 0,
                    cookieAsset: null,
                    vsmBias: 0.01,
                    layers: [0],
                    cookieIntensity: 1,
                    cascadeDistribution: 0.5,
                    cookieOffset: [0, 0],
                    shadowResolution: 1024,
                    cookieScale: [1, 1],
                    enabled: true,
                    shape: 0,
                    range: 8,
                    vsmBlurMode: 1,
                    shadowDistance: 16,
                    type: 'directional',
                    cookieFalloff: true,
                    shadowType: 0,
                },
            },
            rotation: [45, 135, 0],
            tags: [],
            enabled: true,
            children: [],
        },
        'd2b7f9ea-edfa-11eb-9b62-026349a27a7c': {
            position: [0, 5, 0],
            scale: [1, 1, 1],
            name: 'Player',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            resource_id: 'd2b7f9ea-edfa-11eb-9b62-026349a27a7c',
            components: {
                model: {
                    layers: [0],
                    isStatic: false,
                    castShadows: true,
                    castShadowsLightmap: true,
                    lightmapped: false,
                    materialAsset: 52407493,
                    receiveShadows: true,
                    enabled: true,
                    castShadowsLightMap: false,
                    asset: null,
                    type: 'box',
                    lightmapSizeMultiplier: 1,
                    batchGroupId: null,
                },
                script: { enabled: true, order: ['playerController'], scripts: { playerController: { enabled: true, attributes: { speed: 1 } } } },
            },
            rotation: [0, 0, 0],
            tags: [],
            enabled: true,
            children: [],
        },
        'd2b7f9eb-edfa-11eb-9b62-026349a27a7c': {
            position: [0, 0, 0],
            scale: [40, 1, 40],
            name: 'Plane',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            resource_id: 'd2b7f9eb-edfa-11eb-9b62-026349a27a7c',
            components: {
                model: {
                    layers: [0],
                    isStatic: false,
                    castShadows: true,
                    castShadowsLightmap: true,
                    lightmapped: false,
                    materialAsset: null,
                    receiveShadows: true,
                    enabled: true,
                    castShadowsLightMap: false,
                    asset: null,
                    type: 'plane',
                    lightmapSizeMultiplier: 1,
                    batchGroupId: null,
                },
                collision: { enabled: true, type: 'box', halfExtents: [20, 0.5, 20], radius: 0.5, axis: 1, height: 2, asset: null, renderAsset: null },
                rigidbody: {
                    enabled: true,
                    type: 'static',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 1,
                    restitution: 0,
                },
            },
            rotation: [0, 0, 0],
            tags: [],
            enabled: true,
            children: [],
        },
        'dd544343-1c0b-4a61-a61c-52e607d88a5a': {
            name: 'Demo 1',
            tags: [],
            enabled: true,
            resource_id: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            children: [
                'a6484079-48cc-4852-a8ae-9c5dcc22ae9d',
                'af208687-8b82-43e6-8c97-f89b3ef6274e',
                '0de7ccd3-9110-4c7e-861d-6e772f80bc39',
                'cd2d61b3-c45b-41b5-8146-7cad38ab0bab',
                '77a5cf15-4827-4bf0-995a-6792eb511895',
            ],
            position: [0, 0, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                script: {
                    enabled: true,
                    order: ['raycast'],
                    scripts: { raycast: { enabled: true, attributes: { cameraEntity: '946c0121-b491-4539-8a06-53696784b41c' } } },
                },
            },
        },
        'a6484079-48cc-4852-a8ae-9c5dcc22ae9d': {
            name: 'Sphere',
            tags: ['demo'],
            enabled: true,
            resource_id: 'a6484079-48cc-4852-a8ae-9c5dcc22ae9d',
            parent: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            children: [],
            position: [4, 3, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                rigidbody: {
                    enabled: true,
                    type: 'dynamic',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 0.5,
                    restitution: 0.5,
                },
                collision: { enabled: true, type: 'sphere', halfExtents: [0.5, 0.5, 0.5], radius: 0.5, axis: 1, height: 2, asset: null, renderAsset: null },
                script: { enabled: true, order: ['entityProperty'], scripts: { entityProperty: { enabled: true, attributes: {} } } },
                render: {
                    enabled: true,
                    type: 'sphere',
                    asset: null,
                    materialAssets: [52608393],
                    layers: [0],
                    batchGroupId: null,
                    castShadows: true,
                    castShadowsLightmap: true,
                    receiveShadows: true,
                    lightmapped: false,
                    lightmapSizeMultiplier: 1,
                    castShadowsLightMap: true,
                    lightMapped: false,
                    lightMapSizeMultiplier: 1,
                    isStatic: false,
                    rootBone: null,
                },
            },
        },
        'af208687-8b82-43e6-8c97-f89b3ef6274e': {
            name: 'Cylinder',
            tags: ['demo'],
            enabled: true,
            resource_id: 'af208687-8b82-43e6-8c97-f89b3ef6274e',
            parent: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            children: [],
            position: [2, 3, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                rigidbody: {
                    enabled: true,
                    type: 'dynamic',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 0.5,
                    restitution: 0.5,
                },
                collision: {
                    enabled: true,
                    type: 'cylinder',
                    halfExtents: [0.5, 0.5, 0.5],
                    radius: 0.5,
                    axis: 1,
                    height: 1,
                    asset: null,
                    renderAsset: null,
                },
                script: { enabled: true, order: ['entityProperty'], scripts: { entityProperty: { enabled: true, attributes: {} } } },
                render: {
                    enabled: true,
                    type: 'cylinder',
                    asset: null,
                    materialAssets: [52608393],
                    layers: [0],
                    batchGroupId: null,
                    castShadows: true,
                    castShadowsLightmap: true,
                    receiveShadows: true,
                    lightmapped: false,
                    lightmapSizeMultiplier: 1,
                    castShadowsLightMap: true,
                    lightMapped: false,
                    lightMapSizeMultiplier: 1,
                    isStatic: false,
                    rootBone: null,
                },
            },
        },
        '0de7ccd3-9110-4c7e-861d-6e772f80bc39': {
            name: 'Cone',
            tags: ['demo'],
            enabled: true,
            resource_id: '0de7ccd3-9110-4c7e-861d-6e772f80bc39',
            parent: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            children: [],
            position: [0, 3, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                rigidbody: {
                    enabled: true,
                    type: 'dynamic',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 0.5,
                    restitution: 0.5,
                },
                collision: { enabled: true, type: 'cone', halfExtents: [0.5, 0.5, 0.5], radius: 0.5, axis: 1, height: 1, asset: null, renderAsset: null },
                script: { enabled: true, order: ['entityProperty'], scripts: { entityProperty: { enabled: true, attributes: {} } } },
                render: {
                    enabled: true,
                    type: 'cone',
                    asset: null,
                    materialAssets: [52608393],
                    layers: [0],
                    batchGroupId: null,
                    castShadows: true,
                    castShadowsLightmap: true,
                    receiveShadows: true,
                    lightmapped: false,
                    lightmapSizeMultiplier: 1,
                    castShadowsLightMap: true,
                    lightMapped: false,
                    lightMapSizeMultiplier: 1,
                    isStatic: false,
                    rootBone: null,
                },
            },
        },
        'cd2d61b3-c45b-41b5-8146-7cad38ab0bab': {
            name: 'Box',
            tags: ['demo'],
            enabled: true,
            resource_id: 'cd2d61b3-c45b-41b5-8146-7cad38ab0bab',
            parent: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            children: [],
            position: [-4, 3, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                rigidbody: {
                    enabled: true,
                    type: 'dynamic',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 0.5,
                    restitution: 0.5,
                },
                collision: { enabled: true, type: 'box', halfExtents: [0.5, 0.5, 0.5], radius: 0.5, axis: 1, height: 2, asset: null, renderAsset: null },
                script: { enabled: true, order: ['entityProperty'], scripts: { entityProperty: { enabled: true, attributes: {} } } },
                render: {
                    enabled: true,
                    type: 'box',
                    asset: null,
                    materialAssets: [52608393],
                    layers: [0],
                    batchGroupId: null,
                    castShadows: true,
                    castShadowsLightmap: true,
                    receiveShadows: true,
                    lightmapped: false,
                    lightmapSizeMultiplier: 1,
                    castShadowsLightMap: true,
                    lightMapped: false,
                    lightMapSizeMultiplier: 1,
                    isStatic: false,
                    rootBone: null,
                },
            },
        },
        '77a5cf15-4827-4bf0-995a-6792eb511895': {
            name: 'Capsule',
            tags: ['demo'],
            enabled: true,
            resource_id: '77a5cf15-4827-4bf0-995a-6792eb511895',
            parent: 'dd544343-1c0b-4a61-a61c-52e607d88a5a',
            children: [],
            position: [-2, 3, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                rigidbody: {
                    enabled: true,
                    type: 'dynamic',
                    mass: 1,
                    linearDamping: 0,
                    angularDamping: 0,
                    linearFactor: [1, 1, 1],
                    angularFactor: [1, 1, 1],
                    friction: 0.5,
                    restitution: 0.5,
                },
                collision: {
                    enabled: true,
                    type: 'capsule',
                    halfExtents: [0.5, 0.5, 0.5],
                    radius: 0.5,
                    axis: 1,
                    height: 2,
                    asset: null,
                    renderAsset: null,
                },
                script: { enabled: true, order: ['entityProperty'], scripts: { entityProperty: { enabled: true, attributes: {} } } },
                render: {
                    enabled: true,
                    type: 'capsule',
                    asset: null,
                    materialAssets: [52608393],
                    layers: [0],
                    batchGroupId: null,
                    castShadows: true,
                    castShadowsLightmap: true,
                    receiveShadows: true,
                    lightmapped: false,
                    lightmapSizeMultiplier: 1,
                    castShadowsLightMap: true,
                    lightMapped: false,
                    lightMapSizeMultiplier: 1,
                    isStatic: false,
                    rootBone: null,
                },
            },
        },
        'f0aebd00-47c5-4405-aead-fe74fe0ef792': {
            name: '2D Screen',
            tags: [],
            enabled: true,
            resource_id: 'f0aebd00-47c5-4405-aead-fe74fe0ef792',
            parent: 'd2b7f9e7-edfa-11eb-9b62-026349a27a7c',
            children: ['96f37624-0084-4b3c-ba3d-9ce2e9207da0'],
            position: [40, 0, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {
                screen: {
                    enabled: true,
                    screenSpace: true,
                    scaleMode: 'blend',
                    scaleBlend: 0.5,
                    resolution: [1280, 720],
                    referenceResolution: [1920, 1080],
                },
            },
        },
        '96f37624-0084-4b3c-ba3d-9ce2e9207da0': {
            name: 'New Entity',
            tags: [],
            enabled: true,
            resource_id: '96f37624-0084-4b3c-ba3d-9ce2e9207da0',
            parent: 'f0aebd00-47c5-4405-aead-fe74fe0ef792',
            children: [],
            position: [0, 0, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            components: {},
        },
    },
    checkpoint_id: '84703a1d-62be-4766-b1a7-bd15e5e5c68e',
    id: 1200109,
};
